apiVersion: v1
kind: ConfigMap
metadata:
  name: ilmir-config
data:
  LOG_LEVEL: "debug"
  MESSAGE: "Hello, world from ConfigMap!"
  spring.application.name: "Snowflake ID Generator"
  snowflake-settings.starting-epoch: "946684800"
  snowflake-settings.datacenter-id: "1"
  WORKER_ID: "PLACEHOLDER"
  app-settings.json: |
    {
      "featureFlags": {
        "betaMode": true,
        "metricsEnabled": true
      }
    }
